Accounts/urls.py
from django.urls import path
from .import views


urlpatterns = [

       path('register/',views.register,name="register"),
       path('login/',views.login,name="login"),
       path('activate/<uidb64>/<token>/',views.activate,name="activate"),
       path('logoutUser/',views.logoutUser,name="logoutUser"),
       path('forgotpassword/',views.forgotpassword,name="forgotpassword"),
       path('resetpassword_validate/<uidb64>/<token>/',views.resetpassword_validate,name="resetpassword_validate"),
       path("resetpassword/",views.resetpassword,name="resetpassword"),
       path('change_password/',views.change_password,name='change_password'),
   
  

]

itienrarybuddy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('',include("ItineraryAppManagement.urls")),
    path("",include("Accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ItineraryAppManagement/models.py
from pickle import TRUE
from turtle import title
from django.db import models
from django.urls import reverse
from Accounts.models import Account
from django.utils.safestring import mark_safe
from tinymce.models import HTMLField
from phonenumber_field.modelfields import PhoneNumberField

class Continent(models.Model):
    continent_name = models.CharField(max_length=50)
    continent_slug = models.SlugField()
    continent_code = models.CharField(max_length=10)
    def __str__(self):
        return self.continent_name

class Country(models.Model):
    country_name = models.CharField(max_length=50)	
    country_slug = models.SlugField()
    country_code = models.CharField(max_length=10)
    continent = models.ForeignKey(Continent, on_delete=models.CASCADE)
    def __str__(self):
        return self.country_name
    def get_url_country(self):
        return reverse("country_detail",args=[self.country_slug])


class City(models.Model):
    city_name = models.CharField(max_length=50)
    slug = models.SlugField()
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    def __str__(self):
        return self.city_name

    def get_url_city(self):
        return reverse("city_detail",args=[self.country.country_slug,self.slug])

class Itinerarie(models.Model):
    RATING=(
        ('0.5','0.5'),
        ('1','1'),
        ('1.5','1.5'),
        ('2','2'),
        ('2.5','2.5'),
        ('3','3'),
        ('3.5','3.5'),
        ('4','4'),
        ('4.5','4.5'),
        ('5','5'),
    )
    name = models.CharField(max_length=50)
    slug = models.SlugField()
    price = models.IntegerField()
    package = models.CharField(max_length=50, default="5 Days|2 Night")
    currency_code = models.CharField(max_length=5)
    small_description = models.TextField(max_length=175)
    long_description = HTMLField()
    best_itinerary = models.BooleanField()
    rating =models.CharField(max_length=10, choices=RATING, default='')
    image = models.ImageField(upload_to='Itineraries')
    banner=models.ImageField(upload_to='Itineraries', default='')
    state = models.ForeignKey(City, on_delete=models.CASCADE, blank=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    continent = models.ForeignKey(Continent, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    
    def get_url(self):
        return reverse('itinerary_detail',args=[self.country.country_slug,self.slug])

class Customized_Itinerary(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField()
    mobile=models.CharField(max_length=12)
    name_itinerary = models.CharField(max_length=50,default='')
    continent=models.CharField(max_length=50,default='')
    country=models.CharField(max_length=50,default='')
    state=models.CharField(max_length=50,default='')
    budget=models.CharField(max_length=100)
    day=models.CharField(max_length=100)
    night=models.CharField(max_length=100)
    no_of_adults=models.IntegerField()
    no_of_childs=models.IntegerField()
    from_date=models.DateField()
    to_date=models.DateField()
    vacation=models.CharField(max_length=100)
    info=models.TextField(max_length=100)

    def __str__(self):
        return self.name

    def Send_Mail(self):
        return mark_safe('''<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Modal%s">Send Mail</button>''' % self.id)
    title.short_description='Send Mail'
    title.allow_tags = True

    def Mail_modal(self):
        return mark_safe('''<div class="modal fade" id="Modal%s" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            <form method="POST" action="/message/%s">
                <div class="mb-3">
                    <label for="formGroupExampleInput" class="form-label">Email</label>
                    <input type="text" class="form-control" value="%s" name="email" placeholder="Email Address" readonly>
                </div>
                <div class="mb-3">
                    <label for="text-area" class="form-label">Your message here</label>
                    <textarea rows="4" class="form-control" id="text-area" name="message" required></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Send</button>
            </div>
            </form>
            </div>
        </div>
        </div>''' % (self.id,self.id,self.email))
    title.short_description='Send Mail'
    title.allow_tags = True


    
class Cart(models.Model):
    cart_id=models.CharField(max_length=255,blank=True)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    user=models.ForeignKey(Account,on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Itinerarie,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE,null=True)
    is_active=models.BooleanField(default=True)
    

    
    def __unicode__(self):
        return self.product   

class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    #payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100) # this is the total amount paid
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    countryphone_code = models.CharField(max_length=15,null=True,blank=True,default='')
    phone = models.CharField(max_length=15,null=True,blank=True)
    email = models.EmailField(max_length=50)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

 
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.order_number


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Itinerarie, on_delete=models.CASCADE)
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name


class Itinerariesimage(models.Model):
    post= models.ForeignKey(Itinerarie, on_delete=models.CASCADE)
    image= models.ImageField(upload_to="Itineraries")
    
    def _str_(self):
        return self.post.name

class Banner(models.Model):
    
    image=models.ImageField(upload_to='Itineraries')

class Newsletter(models.Model):
    email=models.EmailField(max_length=50)
    created_on = models.DateTimeField(auto_now=True)

Accounts/forms.py
from django import forms
from .models import Account
from django.contrib.auth.password_validation import validate_password
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox

class RegistrationForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput(attrs={
      'class':'form-control',
      'placeholder':'Enter Password',

    }))
    
    confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={
      'class':'form-control',
      'placeholder':'Confirm Password',

    }))
    username=forms.CharField(widget=forms.TextInput(attrs={
      'class':'form-control',
      'placeholder':'Enter Username',

    }))
    email=forms.EmailField(widget=forms.EmailInput(attrs={
      'class':'form-control',
      'placeholder':'Enter Email',

    }))
    
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)
    
    class Meta:
        model=Account
        fields=[ 'email', 'password']



    def clean(self):
        cleaned_data=super(RegistrationForm,self).clean()
        password=cleaned_data.get('password')
        confirm_password=cleaned_data.get('confirm_password')
        if password != confirm_password:
          # print(range(password))
          raise forms.ValidationError(
            "password does not match"   ) 
        
        # elif range(password) < 8:
        #   raise forms.ValidationError(
        #     "Password too short"   ) 

class UserprofileForm(forms.ModelForm):
  class Meta:
    model =Account
    fields = ("username","email","mobile","nationality","country","profile_pic")  
    
  def save(self, commit: True):
    profileupdate = self.instance
    profileupdate.username = self.cleaned_data['username']
    profileupdate.email = self.cleaned_data['email']
    profileupdate.mobile = self.cleaned_data['mobile']
    profileupdate.nationality = self.cleaned_data['nationality']
    profileupdate.country = self.cleaned_data['country']
    
    if self.cleaned_data['profile_pic']:
      profileupdate.profile_pic = self.cleaned_data['profile_pic']
    
    if commit:
      profileupdate.save()
    return profileupdate

templates/includes/alert.html
<style>
.alert-success{
    color: #ffffff;
    background-color: rgb(40 54 116);
    border-color: rgb(19 180 128);
    border-left: 7px solid rgb(21 183 127) !important;
    border: 2px solid rgb(40 54 116);
    font-weight: 400 !important;
    font-size: 18px !important;
    padding: 0.5rem 1rem;
}
.alert-error{
    color: #ffffff;
    background-color: rgb(255 0 0 / 92%);
    border-color: #f8f9fa;
    border-left: 7px solid #00cc66 !important;
    border: 2px solid #dc3545;
    font-weight: 400 !important;
    font-size: 18px !important;
    padding: 0.5rem 1rem;
}
</style>
{% if messages %} {% for message in messages %}
<div id="message" style="position: fixed;bottom: 2%;left: 0;z-index: 10;width: auto;" class="container">
    <div{% if message.tags %} class="alert alert-{{ message.tags }} fs-6 fw-bold" {% endif %} role="alert">
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} ERROR:{% endif %} {{ message }}</li>
        {% endfor %}
</div>
</div>
{% endif %}

<script>
    setTimeout(function() {
    document.getElementById("message").style = "display:none;";
}, 5000); 
</script>

templates/includes/footer.html
{% load static %}
<footer class="custm_bg2">
    <div class="container pt-4">
        <div class="newsletter py-2">
            <form method="POST" action="{% url 'newsletter' %}" class="mb-2">
                {% csrf_token %}
                <div class="input-group m-auto w-sm-100 w-50">
                    <input type="email" name='email' class="form-control bg-transparent text-white" placeholder="Subscribe For Newsletter" aria-label="Username" aria-describedby="basic-addon1">
                    <button type='submit' value='newsletter' class="custm_bg btn border-0"><span class="border-0 input-group-text custm_bg" id="basic-addon1"><i class="fas fa-arrow-right-long"></i></span></button>
                </div>
            </form>
            <p class="text-white text-center p-0 m-0">To know more about latest update</p>
        </div>
    </div>
    <div class="container-fluid">
        <div class="links custm_bg py-4 row row-cols-1 row-cols-md-2 row-cols-lg-4 justify-content-center align-items-start">
            <div class="col">
                <ul class="nav-item">
                    <h5 class="text-white">Quick Links</h5>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'profile' request.user.id %}" class="nav-link text-white">My Profile</a>
                    </li>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'dashboard' %}" class="nav-link text-white">Dashboard</a>
                    </li>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'home' %}" class="nav-link text-white">FAQs</a>
                    </li>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'home' %}" class="nav-link text-white">Privacy Policy</a>
                    </li>
                </ul>
            </div>
            <div class="col">
                <ul class="nav-item">
                    <h5 class="text-white">Useful Links</h5>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'login' %}" class="nav-link text-white">Login</a>
                    </li>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'register' %}" class="nav-link text-white">Register</a>
                    </li>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'change_password' %}" class="nav-link text-white">Change Password</a>
                    </li>
                </ul>
            </div>
            <div class="col">
                <ul class="nav-item">
                    <h5 class="text-white">Itinerary Pages</h5>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'customized_itinerary' %}" class="nav-link text-white">Customized Itinerary</a>
                    </li>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'about' %}" class="nav-link text-white">About us</a>
                    </li>
                    <li class="nav-link text-white p-0">
                        <a href="{% url 'cart' %}" class="nav-link text-white">My Cart</a>
                    </li>
                </ul>
            </div>
            <div class="col">
                <ul class="nav-item">
                    <h5 class="text-white">Contact Us</h5>
                    <li class="nav-link text-white">info@itinerarybuddy.com</li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/includes/header.html
<!-- navbar start -->
<nav class="navbar navbar-expand-lg navbar-light header p-0" id="myHeader">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="/static/images/logo.jpg" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 fs-5">
                <li class="nav-item mx-1">
                    <a class="nav-link {% if '/' ==  request.path %}active{% endif %}" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item mx-1">
                    <a class="nav-link  {% if '/customized_itinerary' ==  request.path %}active{% endif %}" href="{% url 'customized_itinerary' %}">Customized Itinerary</a>
                </li>
                {% if user.id is None %}
                <div class="dropdown">
                    <button class="btn btn-white dropdown-toggle fs-5 text-muted" style="font-weight:400 !important;" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        Account
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li>
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                        </li>
                    </ul>
                </div>

                {% else %}
                <div class="dropdown">
                    <button class="btn btn-white dropdown-toggle fs-5 text-muted" style="font-weight:400 !important;" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li class="nav-item mx-1">
                            <small class="title text-muted">Welcome {{ user.username }}</small>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'dashboard' %}">Dashboard</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'logoutUser' %}">Logout</a>
                        </li>
                    </ul>
                </div>
                {% endif %}
                <li class="nav-item mx-1">
                    <a href="{% url 'cart' %}" class="btn custm_bg2 custm_bg2 position-relative">
                        <i class="fa fa-shopping-cart text-white lh-base"></i>
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill custm_bg">
                            {{cart_count}}
                          <span class="visually-hidden">unread messages</span>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- navbar end -->

templates/includes/send_email.html
{% extends "admin/change_form.html" %}{% load i18n %}{% block submit_buttons_bottom %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<style>
    .submit-row a.deletelink {
        display: block;
        background: #ba2121;
        border-radius: 4px;
        padding: 10px 15px;
        height: 35px;
        line-height: 15px;
        color: #fff;
    }

    h1,
    h2 {
        font-size: 15px;
    }
</style>
<div class="d-block text-end container">
    <button type="button" class="btn btn-primary py-1 px-2 mb-3" data-bs-toggle="modal" data-bs-target="#mailModal" style="background: #79aec8;">
        Send Mail
    </button>
</div>
<div class="modal fade" id="mailModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Send Email</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <input type="hidden" class="form-control" disabled id="custm_name" name="name"
                    aria-describedby="emailHelp">
                    <label for="exampleInputEmail1" class="form-label">Email address</label>
                    <input type="email" class="form-control" disabled id="emailname" name="email"
                        aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Mail Subject</label>
                    <input type="text" class="form-control" id="subject" name="subject"
                        aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="text-area" class="form-label">Your message here</label>
                    <textarea rows="4" class="form-control" id="text-area" name="message" style="width: 100%;"
                        required></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="formsubmit" style="background: #79aec8;">Submit</button>
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        let mail = $('#id_email').val();
        let custmname = $('#id_name').val();
        $('#emailname').val(mail)
        $('#custm_name').val(custmname)
        $("#formsubmit").click(function (event) {
            event.preventDefault();
            var formData = {
                name : custmname,
                email: mail,
                subject: $("#subject").val(),
                message: $("#text-area").val(),
            };
            $.ajax({
                type: "POST",
                url: "/message",
                data: formData,
                dataType: "json",
                encode: true,
            })
            location.reload();
            alert("Mail Sended successfuly")
        });
    });
</script>
{{ block.super }}
{% endblock %}